# Generated by Django 4.2.14 on 2024-07-16 21:19

from django.db import migrations, models

def create_data(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account(name = "Chase", email = "copelandc6@gmail.com", password = "12345")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
